### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.Ident, not *ast.KeyValueExpr

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#16]
```
$ unused -v github.com/gonum/graph/...
panic: interface conversion: ast.Expr is *ast.Ident, not *ast.KeyValueExpr

goroutine 1 [running]:
panic(0x68e1c0, 0xc8261e7640)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
honnef.co/go/unused.(*Checker).Visit(0xc8202a13a0, 0x7f7006e12068, 0xc821d21740, 0x0, 0x0)
    /home/dominikh/prj/src/honnef.co/go/unused/unused.go:132 +0x719
go/ast.Walk(0x7f7006e11f80, 0xc8202a13a0, 0x7f7006e12068, 0xc821d21740)
    /usr/lib/go/src/go/ast/walk.go:52 +0x56
go/ast.Walk(0x7f7006e11f80, 0xc8202a13a0, 0x7f7006e51600, 0xc825051220)
    /usr/lib/go/src/go/ast/walk.go:284 +0x2e0b
go/ast.walkStmtList(0x7f7006e11f80, 0xc8202a13a0, 0xc824f11300, 0xb, 0x10)
    /usr/lib/go/src/go/ast/walk.go:32 +0xd5
go/ast.Walk(0x7f7006e11f80, 0xc8202a13a0, 0x7f7006e51630, 0xc82505dbf0)
    /usr/lib/go/src/go/ast/walk.go:224 +0x3e1e
go/ast.Walk(0x7f7006e11f80, 0xc8202a13a0, 0x7f7006e12278, 0xc82505dc20)
    /usr/lib/go/src/go/ast/walk.go:344 +0xb46
go/ast.walkDeclList(0x7f7006e11f80, 0xc8202a13a0, 0xc824f13400, 0x12, 0x20)
    /usr/lib/go/src/go/ast/walk.go:38 +0xd5
go/ast.Walk(0x7f7006e11f80, 0xc8202a13a0, 0x7f7006da99c0, 0xc824f1d300)
    /usr/lib/go/src/go/ast/walk.go:353 +0x29b9
honnef.co/go/unused.(*Checker).Check(0xc8202a13a0, 0xc82046c100, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/dominikh/prj/src/honnef.co/go/unused/unused.go:236 +0xa29
main.main()
    /home/dominikh/prj/src/honnef.co/go/unused/cmd/unused/main.go:64 +0x236
```

**Comment by kortschak** [comment]
The minimal package set to get this failure is "github.com/gonum/graph/internal/set".

**Comment by dominikh** [comment]
```
package pkg

type M map[int]int

func Fn() {
    var n M
    for range []M{n} {
    }
}
```

is the minimal example reproducing the issue.

**Comment by dominikh** [comment]
Correction, 

```
package pkg

type M map[int]int

func Fn() {
    var n M
    _ = []M{n}
}
```

is.
