### ISSUE TITLE
unused cmd/internal/obj/x86 panics

### ISSUE THREAD

**Issue by mwhudson** [dominikh/go-unused#2]
Haven't looked into this in the slightest!

``` shellsession
mwhudson@aeglos:golang$ unused cmd/internal/obj/x86
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x46eeaf]

goroutine 1 [running]:
panic(0x610e00, 0xc82000e150)
    /opt/opensource/go/src/runtime/panic.go:500 +0x18e
honnef.co/go/unused.(*Checker).Check.func3(0x7ff2c7cc38d8, 0xc821afa2c0, 0x7ff2c7cc3610, 0x40e57e)
    /opt/opensource/gopath/src/honnef.co/go/unused/unused.go:106 +0x3af
honnef.co/go/unused.visitor.Visit(0xc825341200, 0x7ff2c7cc38d8, 0xc821afa2c0, 0x7a4e08, 0x0)
    /opt/opensource/gopath/src/honnef.co/go/unused/unused.go:289 +0x33
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7cc38d8, 0xc821afa2c0)
    /opt/opensource/go/src/go/ast/walk.go:52 +0x56
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7cc38a8, 0xc820e253c0)
    /opt/opensource/go/src/go/ast/walk.go:143 +0x1bdd
go/ast.walkExprList(0x7ff2c7cc3610, 0xc825341200, 0xc82267dcd0, 0x1, 0x1)
    /opt/opensource/go/src/go/ast/walk.go:26 +0x7f
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7cc3878, 0xc821afa300)
    /opt/opensource/go/src/go/ast/walk.go:207 +0x2935
go/ast.walkStmtList(0x7ff2c7cc3610, 0xc825341200, 0xc822556200, 0x9, 0x10)
    /opt/opensource/go/src/go/ast/walk.go:32 +0x7f
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7d5c0f8, 0xc8214f9e60)
    /opt/opensource/go/src/go/ast/walk.go:224 +0x21b3
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7cc37e8, 0xc8214f9ec0)
    /opt/opensource/go/src/go/ast/walk.go:344 +0x11f9
go/ast.walkDeclList(0x7ff2c7cc3610, 0xc825341200, 0xc822556400, 0xb, 0x10)
    /opt/opensource/go/src/go/ast/walk.go:38 +0x7f
go/ast.Walk(0x7ff2c7cc3610, 0xc825341200, 0x7ff2c7cdac48, 0xc8225b0900)
    /opt/opensource/go/src/go/ast/walk.go:353 +0x2eed
honnef.co/go/unused.(*Checker).Check(0xc8220cbec0, 0xc82000e860, 0x1, 0x1, 0x1, 0x1, 0xc82000e849, 0xc820010900, 0x3)
    /opt/opensource/gopath/src/honnef.co/go/unused/unused.go:132 +0xbf9
main.main()
    /opt/opensource/gopath/src/honnef.co/go/unused/cmd/unused/main.go:64 +0x14e
```

**Comment by dmitshur** [comment]
I can reproduce with `go version go1.6 darwin/amd64` and latest `unused` as of 2 minutes ago.

**Comment by dominikh** [comment]
Can reproduce, will fix.
