### ISSUE TITLE
panic: interface conversion: types.Type is *types.Pointer, not *types.Struct

### ISSUE THREAD

**Issue by kyoh86** [dominikh/go-unused#52]
It's panicked...

```
$ unused -exported ./...
panic: interface conversion: types.Type is *types.Pointer, not *types.Struct

goroutine 4276 [running]:
panic(0x2ad8c0, 0xc56df7b380)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
honnef.co/go/unused.getField(0x42c500, 0xc42d1c8db0, 0x1, 0x2bd2c0)
	/go/src/honnef.co/go/unused/unused.go:952 +0x172
honnef.co/go/unused.(*Checker).processSelections.func1(0xc4288ed5a0, 0xc42dd7ccd0, 0x0)
	/go/src/honnef.co/go/unused/unused.go:557 +0x1f7
honnef.co/go/unused.(*Checker).processSelections(0xc4200e4000, 0xc434169a20)
	/go/src/honnef.co/go/unused/unused.go:567 +0x129
honnef.co/go/unused.(*Checker).Check(0xc4200e4000, 0xc42021d4c0, 0xc57c5d79a8, 0xc57c5f0c90, 0x4c200)
	/go/src/honnef.co/go/unused/unused.go:213 +0x109
honnef.co/go/unused.(*LintChecker).Lint(0xc4200c81a0, 0xc57c5d7980)
	/go/src/honnef.co/go/unused/unused.go:66 +0x3cc
honnef.co/go/unused.(*LintChecker).Lint-fm(0xc57c5d7980)
	/go/src/honnef.co/go/unused/unused.go:38 +0x34
honnef.co/go/lint.(*Linter).Lint.func1(0xc57c5e47d0, 0xc57c5d78c0, 0xc57c5d7920)
	/go/src/honnef.co/go/lint/lint.go:184 +0x4f6
created by honnef.co/go/lint.(*Linter).Lint
	/go/src/honnef.co/go/lint/lint.go:195 +0x72d
```

**Comment by dominikh** [comment]
I'll need a self-contained code sample that triggers the panic.

**Comment by kyoh86** [comment]
OK, I'll prepare it ASAP.

**Comment by dmitshur** [comment]
> I'll need a self-contained code sample that triggers the panic.

Here you go:

```Go
package main

func main() {
	var p P
	_ = p.n
}

type T0 struct {
	n int
}

type T1 struct {
	T0
}

type P *T1
```
